from pydantic import BaseModel, Field
from typing import List, Optional, Dict


class ActionPlan(BaseModel):
    cooling_level: Optional[str] = Field(default=None, description="Cooling control action")
    send_alert: bool = Field(default=False, description="Whether to send an alert")
    maintenance_required: bool = Field(default=False, description="Whether maintenance is required")


class DecisionOutput(BaseModel):
    device_id: str = Field(..., description="Device ID associated with the decision")
    risk_score: int = Field(..., ge=0, le=100, description="Calculated risk score")
    risk_level: str = Field(..., description="Risk level such as low, medium, high")
    anomalies: List[str] = Field(default_factory=list, description="Detected anomalies")
    recommendation: str = Field(..., description="Recommended action or summary")
    action: ActionPlan = Field(..., description="Structured action plan")
    agent_explanation: Optional[str] = Field(default=None, description="Natural language explanation generated by the system")